
server:
  port: 8080
  servlet:
    context-path: /sicred/app

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postegres
    url: jdbc:postgresql://localhost:5432/pautaDb
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
   
   